version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretrootpassword
      - MYSQL_DATABASE=web_bh_online
      - MYSQL_USER=myrootuser
      - MYSQL_PASSWORD=mysecretpassword
    ports:
      - '3308:3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: